### ISSUE TITLE
Allow bot to automatically join threads + read and respond to threads

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-scripting-faq-bot#13]

**Comment by 7dev7urandom** [comment]
Needs alpha version of discord.py, conversion to pycord, or rewrite to JS

**Comment by Hatchibombotar** [comment]
https://github.com/Bedrock-OSS/bedrock-scripting-faq-bot/commit/7198f10be5dde60a4dd86b9556f37e162ddeccc4
