### ISSUE TITLE
No consistent code style (PEP-8)

### ISSUE THREAD

**Issue by aym-i** [Bedrock-OSS/bedrock-scripting-faq-bot#23]
Hi!
There are a lot of problems with the code, mainly with the PEP-8 style guideline:
1. The file name
2. The mix of `CamelCase` and `snake_case`
3. Some of the code is uncommented.
4. Bare `except` statements...

**Comment by Dreamedc2015** [comment]
pep-8 is archaic and stupid imo. while case should be consistent pep-8 disallows things like importing multiple things on the same line e.g `import os, system` and enforces a 4 space indent. just my opinion
https://www.python.org/dev/peps/pep-0008/
